export const CREATE_SET_INVERTER_CONFIG = 'CREATE_SET_INVERTER_CONFIG';
export const CREATE_SET_RUNTIME_CONFIG = 'CREATE_SET_RUNTIME_CONFIG';
export const CREATE_SET_CURRENT_STATE = 'CREATE_SET_CURRENT_STATE';
